### PR TITLE
CuPy to GpuMat debuged

### PR DESCRIPTION
**Pull request by HitoshiUchida**
Copying Cupy memory to gpuMat was successed.
Please check it.

### CODE REVIEW

**Comment by manbehindthemadness** [comment]
Great stuff, I have performed a series of tests on my end and it seems to be working perfectly. I have only tested 3 dims however.

**Comment by manbehindthemadness** [comment]
Hmmm, should this remain a box of experiments, or should I get round to making a utility package or some such and publish it to pypi?

**Comment by HitoshiUchida** [comment]
Ah, YES.
I think that we should publish this results espetially cupy-gpuMat combination.
However, cupy -> gpuMat is only memcpy version. we should develop pointer pass method.
How doy think ?

**Comment by manbehindthemadness** [comment]
The memory pointer method would by far be the fastest; However, I  not sure if cudawarped has released that logic just yet (I know he's working on it) alternatively, whilst all this works in a single GPU / Tegra environment, multiple GPUs need to be considered.

**Comment by HitoshiUchida** [comment]
At first, I apologize too late reply. I was busy in these weeks. Cause my wife's father has gone to next stage.
Anyway, pointer type developing is difficult in this time, so I agree to release in this phase.

Best Regards,

**Comment by manbehindthemadness** [comment]
I'm in the same boat, middle of a job switch, going to table the release until I can get my new lab setup.

**Pull request merged**
